<html>
    <head>
        <title>$title$</title>

        <link type="text/css" rel="stylesheet" href="/css/libs/font-awesome/font-awesome.css" media="screen"></link>
        <link type="text/css" rel="stylesheet" href="/css/libs/bootstrap/bootstrap.css" media="screen"></link>
        <script src="/js/libs/jquery.js"></script>
        <script src="/js/libs/bootstrap.js"></script>
        <script data-main="js/bootstrap" src="/js/libs/require.js"></script>
    </head>
    <body>
        <div class="content">$body$</div>
    </body>
</html>